name: screens

on:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  screens:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: setup node
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: ./**/package-lock.json
          node-version: 24.x

      - name: setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: src/**/packages.lock.json
          global-json-file: global.json

      - name: trust dev-certs
        run: dotnet dev-certs https --trust

      - name: install workloads
        run: dotnet workload restore && dotnet workload install wasm-tools

      - name: restore
        run: dotnet restore --locked-mode

      - name: capture screens
        run: dotnet run --project tool/ScreenCap/ScreenCap.csproj --no-restore

      - name: upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: screens
          path: tool/ScreenCap/data

      - name: update screens
        if: ${{ startsWith(github.head_ref, 'release/') }}
        run: rm -rf content/screens && mv tool/ScreenCap/data content/screens

      - name: commit
        uses: devops-infra/action-commit-push@v1
        if: ${{ startsWith(github.head_ref, 'release/') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "[AUTO]"
          commit_message: "Update screenshots"
          target_branch: feature/update-screens

      - name: create pr
        uses: devops-infra/action-pull-request@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: "**Automated pull request**<br><br>Updated screenshots."
          title: Update screenshots
